name: Docker Image CI

on:
  push:
    branches: [ "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_ PASSWORD
    - name: build image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/kube-backup:${{ github.sha }}
    - name: push image
      run: |
        docker push ${{secrets.DOCKER_USER}}/kube-backup
